---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
        tier: chaincode
        track: stable
    spec:
       containers:
        - image: {{ .Values.repository }}
          name: {{ .Values.name }}
          imagePullPolicy: Always
          ports:
            - name: {{ .Values.svc.portName }}-p
              containerPort: {{ .Values.port }}
          env:
            - name: CHAINCODE_ID
              value: "{{ .Values.CCID }}"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
            - name: CORE_CHAINCODE_ID_NAME
              value: "{{.Values.name}}"
---

