---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
      app: {{ .Values.name }}
      tier: chaincode
      track: stable
  ports:
    - protocol: TCP
      targetPort: {{ .Values.port }}
      port: {{ .Values.port }}
      name: {{ .Values.svc.portName }}-p
  type: ClusterIP

